language: minimal
dist: bionic

env:
  - ZOLA_VERSION=v0.9.0

script:
  - curl -L https://github.com/getzola/zola/releases/download/$ZOLA_VERSION/zola-$ZOLA_VERSION-x86_64-unknown-linux-gnu.tar.gz | tar xz
  - ./zola build
  - echo "mckeogh.tech" > public/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: public/
  on:
    branch: master
