baseURL: "https://fmckeogh.github.io"
languageCode: "en-gb"
title: "fmckeogh.github.io"
theme: "novela"
pygmentsstyle: "monokai"
paginate: 10
social:
  twitter: "https://twitter.com/chocol4te1"
  github: "https://github.com/fmckeogh"
  instagram: "https://www.instagram.com/ferdiamckeogh/"
  linkedin: "https://www.linkedin.com/in/ferdia-mckeogh-5b042b194"
taxonomies:
  author: authors
markup:
  goldmark:
    renderer:
      unsafe: true
